apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scalar-workflow-web.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scalar-workflow-web.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.web.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "scalar-workflow-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "scalar-workflow-web.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "scalar-workflow-web.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-container
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - name: web-port
              containerPort: {{ .Values.web.port }}
              protocol: TCP
          env:
          - name: SERVER_ENV
            value: {{ .Values.web.serverEnv }}
          - name: WF_API
            value: {{ .Values.web.wfApi }}
          - name: AWS_PROJECT_REGION
            value: {{ .Values.web.aws.awsProjectRegion }}
          - name: AWS_COGNITO_REGION
            value: {{ .Values.web.aws.awsCognitoRegion }}
          - name: AWS_USER_POOLS_ID
            value: {{ .Values.web.aws.awsUserPoolsId }}
          - name: AWS_USER_POOLS_WEB_CLIENT_ID
            value: {{ .Values.web.aws.awsUserPoolsWebClientId }}
          - name: ROOT_WORKAREA_ID
            value: {{ .Values.web.storage.rootWorkareaId | quote }}
          - name: AUTH_PROVIDER
            value: {{ .Values.web.authProvider }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
