apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  labels:
    {{- include "scalar-workflow-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: web-port
      protocol: TCP
      name: web-service-port
  selector:
    {{- include "scalar-workflow-web.selectorLabels" . | nindent 4 }}
