apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Chart.Name }}-secret
  namespace: {{ .Release.Namespace }}
data:
  {{- if .Values.dataPopulation.scalardb.configData }}
  {{.Values.dataPopulation.scalardb.config }}: |-
{{ .Values.dataPopulation.scalardb.configData | b64enc  | indent 4 }}
  {{- end }}
  {{- if .Values.dataPopulation.scalardb.username }}
  SCALARDB__USERNAME: |-
{{ .Values.dataPopulation.scalardb.username | b64enc  | indent 4 }}
  {{- end }}
  {{- if .Values.dataPopulation.scalardb.password }}
  SCALARDB__PASSWORD: |-
{{ .Values.dataPopulation.scalardb.password | b64enc  | indent 4 }}
  {{- end }}
