apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  {{.Values.api.springBootConfig.name }}: |-
{{ .Values.api.springBootConfig.data | indent 4 }}
  {{.Values.api.boxConfig.name }}: |-
{{ .Values.api.boxConfig.data | indent 4 }}
  {{.Values.api.scalardbConfig.name }}: |-
{{ .Values.api.scalardbConfig.data | indent 4 }}
