apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Chart.Name }}-secret
  namespace: {{ .Release.Namespace }}
data:
  {{.Values.api.springBootConfig.name }}: |-
{{ .Values.api.springBootConfig.data | b64enc  | indent 4 }}
  {{.Values.api.boxConfig.name }}: |-
{{ .Values.api.boxConfig.data | b64enc  | indent 4 }}
  {{.Values.api.scalardbConfig.name }}: |-
{{ .Values.api.scalardbConfig.data | b64enc  | indent 4 }}
