apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Chart.Name }}-secret
  namespace: {{ .Release.Namespace }}
data:
  {{- if .Values.api.spring.datasource.url }}
  SPRING__DATASOURCE__URL: |-
{{ .Values.api.spring.datasource.url | b64enc  | indent 4 }}
  {{- end }}
  {{- if .Values.api.spring.datasource.username }}
  SPRING__DATASOURCE__USERNAME: |-
{{ .Values.api.spring.datasource.username | b64enc  | indent 4 }}
  {{- end }}
  {{- if .Values.api.spring.datasource.password }}
  SPRING__DATASOURCE__PASSWORD: |-
{{ .Values.api.spring.datasource.password | b64enc  | indent 4 }}
  {{- end }}
  {{- if .Values.api.springBootConfig.data }}
  {{.Values.api.springBootConfig.name }}: |-
{{ .Values.api.springBootConfig.data | b64enc  | indent 4 }}
  {{- end }}
  {{- if .Values.api.storage.box.configData }}
  {{.Values.api.storage.box.config }}: |-
{{ .Values.api.storage.box.configData | b64enc  | indent 4 }}
  {{- end }}
  {{- if .Values.api.scalardb.configData }}
  {{.Values.api.scalardb.config }}: |-
{{ .Values.api.scalardb.configData | b64enc  | indent 4 }}
  {{- end }}
  {{- if .Values.api.scalardb.username }}
  SCALARDB__USERNAME: |-
{{ .Values.api.scalardb.username | b64enc  | indent 4 }}
  {{- end }}
  {{- if .Values.api.scalardb.password }}
  SCALARDB__PASSWORD: |-
{{ .Values.api.scalardb.password | b64enc  | indent 4 }}
  {{- end }}
  {{- if .Values.api.app.adminUser.password }}
  APP__ADMIN_USER__PASSWORD: |-
{{ .Values.api.app.adminUser.password | b64enc  | indent 4 }}
  {{- end }}
  {{- if .Values.api.storage.box.clientSecret }}
  STORAGE__BOX__CLIENT_SECRET: |-
{{ .Values.api.storage.box.clientSecret | b64enc  | indent 4 }}
  {{- end }}
  {{- if .Values.api.storage.box.privateKey }}
  STORAGE__BOX__PRIVATE_KEY: |-
{{ .Values.api.storage.box.privateKey | b64enc  | indent 4 }}
  {{- end }}
  {{- if .Values.api.storage.box.passphrase }}
  STORAGE__BOX__PASSPHRASE: |-
{{ .Values.api.storage.box.passphrase | b64enc  | indent 4 }}
  {{- end }}
  {{- if .Values.api.storage.awsS3.accessKeyId }}
  STORAGE__AWS_S3__ACCESS_KEY_ID: |-
{{ .Values.api.storage.awsS3.accessKeyId | b64enc  | indent 4 }}
  {{- end }}
  {{- if .Values.api.storage.awsS3.secretAccessKey }}
  STORAGE__AWS_S3__SECRET_ACCESS_KEY: |-
{{ .Values.api.storage.awsS3.secretAccessKey | b64enc  | indent 4 }}
  {{- end }}
  {{- if .Values.api.storage.gcs.serviceAccountName }}
  STORAGE__GCS__SERVICE_ACCOUNT_NAME: |-
{{ .Values.api.storage.gcs.serviceAccountName | b64enc  | indent 4 }}
  {{- end }}
  {{- if .Values.api.storage.gcs.serviceAccountPrivateKey }}
  STORAGE__GCS_SERVICE_ACCOUNT_PRIVATE_KEY: |-
{{ .Values.api.storage.gcs.serviceAccountPrivateKey | b64enc  | indent 4 }}
  {{- end }}
  {{- if .Values.api.storage.azureBlob.storageAccountName }}
  STORAGE__AZURE_BLOB__STORAGE_ACCOUNT_NAME: |-
{{ .Values.api.storage.azureBlob.storageAccountName | b64enc  | indent 4 }}
  {{- end }}
  {{- if .Values.api.storage.azureBlob.storageAccountKey }}
  STORAGE__AZURE_BLOB_STORAGE_ACCOUNT_KEY: |-
{{ .Values.api.storage.azureBlob.storageAccountKey | b64enc  | indent 4 }}
  {{- end }}
  {{- if .Values.api.sms.twilio.token }}
  SMS__TWILIO__TOKEN: |-
{{ .Values.api.sms.twilio.token | b64enc  | indent 4 }}
  {{- end }}
  {{- if .Values.api.sms.awsSns.accessKey }}
  SMS__AWS_SNS__ACCESS_KEY: |-
{{ .Values.api.sms.awsSns.accessKey | b64enc  | indent 4 }}
  {{- end }}
  {{- if .Values.api.sms.awsSns.secretKey }}
  SMS__AWS_SNS__SECRET_KEY: |-
{{ .Values.api.sms.awsSns.secretKey | b64enc  | indent 4 }}
  {{- end }}
  {{- if .Values.api.email.sendgrid.apiKey }}
  EMAIL__SENDGRID__API_KEY: |-
{{ .Values.api.email.sendgrid.apiKey | b64enc  | indent 4 }}
  {{- end }}
  {{- if .Values.api.email.awsSes.accessKey }}
  EMAIL__AWS_SES__ACCESS_KEY: |-
{{ .Values.api.email.awsSes.accessKey | b64enc  | indent 4 }}
  {{- end }}
  {{- if .Values.api.email.awsSes.secretKey }}
  EMAIL__AWS_SES__SECRET_KEY: |-
{{ .Values.api.email.awsSes.secretKey | b64enc  | indent 4 }}
  {{- end }}
  {{- if .Values.api.crypto.keyPair.privateKey }}
  CRYPTO__KEY_PAIR__PRIVATE_KEY: |-
{{ .Values.api.crypto.keyPair.privateKey | b64enc  | indent 4 }}
  {{- end }}
  {{- if .Values.api.authentication.providers.awsCognito.accessKey }}
  AUTHENTICATION__PROVIDERS__AWS_COGNITO__ACCESS_KEY: |-
{{ .Values.api.authentication.providers.awsCognito.accessKey | b64enc  | indent 4 }}
  {{- end }}
  {{- if .Values.api.authentication.providers.awsCognito.secretKey }}
  AUTHENTICATION__PROVIDERS__AWS_COGNITO__SECRET_KEY: |-
{{ .Values.api.authentication.providers.awsCognito.secretKey | b64enc  | indent 4 }}
  {{- end }}
  {{- if .Values.api.authentication.providers.oauth2.google.clientSecret }}
  AUTHENTICATION__PROVIDERS__OAUTH2__GOOGLE__CLIENT_SECRET: |-
{{ .Values.api.authentication.providers.oauth2.google.clientSecret | b64enc  | indent 4 }}
  {{- end }}
  {{- if .Values.api.authentication.providers.oauth2.box.clientSecret }}
  AUTHENTICATION__PROVIDERS__OAUTH2__BOX__CLIENT_SECRET: |-
{{ .Values.api.authentication.providers.oauth2.box.clientSecret | b64enc  | indent 4 }}
  {{- end }}
  {{- if .Values.api.authentication.staticJwt.secret }}
  AUTHENTICATION__STATIC_JWT__SECRET: |-
{{ .Values.api.authentication.staticJwt.secret | b64enc  | indent 4 }}
  {{- end }}
