apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Chart.Name }}-secret
  namespace: {{ .Release.Namespace }}
data:
  {{- if .Values.api.springBootConfig.data }}
  {{.Values.api.springBootConfig.name }}: |-
{{ .Values.api.springBootConfig.data | b64enc  | indent 4 }}
  {{- end }}

  {{- if .Values.api.storage.box.configData }}
  {{.Values.api.storage.box.config }}: |-
{{ .Values.api.storage.box.configData | b64enc  | indent 4 }}
  {{- end }}

  {{- if .Values.api.scalardb.configData }}
  {{.Values.api.scalardb.config }}: |-
{{ .Values.api.scalardb.configData | b64enc  | indent 4 }}
  {{- end }}
